export const regioniEnum : String[]= [
    "ABRUZZO", "BASILICATA", "CALABRIA", "CAMPANIA",
    "EMILIA_ROMAGNA", "FRIULI_VENEZIA_GIULIA", "LAZIO",
    "LIGURIA", "LOMBARDIA", "MARCHE", "MOLISE", "PIEMONTE",
    "PUGLIA", "SARDEGNA", "SICILIA", "TOSCANA", "TRENTINO_ALTO_ADIGE",
    "UMBRIA", "VALLE_DAOSTA", "VENETO"
]

export const regioniEnumFormattate : String[]= [
    "ABRUZZO", "BASILICATA", "CALABRIA", "CAMPANIA",
    "EMILIA ROMAGNA", "FRIULI VENEZIA GIULIA", "LAZIO",
    "LIGURIA", "LOMBARDIA", "MARCHE", "MOLISE", "PIEMONTE",
    "PUGLIA", "SARDEGNA", "SICILIA", "TOSCANA", "TRENTINO ALTO ADIGE",
    "UMBRIA", "VALLE DAOSTA", "VENETO"
]